django-ecommerce-master/core/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    ProductsView,
    about,
    add_single_item_to_cart,
    remove_all_items_from_cart,
    ContactView,
    confirm_offer,
    AccountInfoView
)

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),

    path('add-to-cart/<slug>/<int:count>/', add_to_cart, name='add-to-cart'),
    path('add-single-item-to-cart/<slug>/', add_single_item_to_cart,
         name='add-single-item-to-cart'),
    path('remove-from-cart/<slug>/<int:count>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('remove-all-items-from-cart/<slug>/', remove_all_items_from_cart,
         name='remove-all-items-from-cart'),
    path('products/<main_id>/<sub_id>', ProductsView.as_view(), name='show-sub-category'),
    path('products/<main_id>/', ProductsView.as_view(), name='show-main-category'),
    path('products/', ProductsView.as_view(), name='products'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('about-us/', about, name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('confirm-offer/', confirm_offer, name='confirm-offer'),
    path('account-info/', AccountInfoView.as_view(), name='account-info'),
]

app_name = 'core'

django-ecommerce-master/core/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django.utils import timezone


# USER
# "fields": {
#     "password": "pbkdf2_sha256$150000$3riG7P2EZFxw$TZ94aNgQsd7fMROxxK2a/ncyxQENdDt2KOesEQ6m5gE=",
#     "last_login": "2022-04-29T14:10:16.710Z",
#     "is_superuser": true,
#     "username": "DMaxim",
#     "first_name": "",
#     "last_name": "",
#     "email": "maksim.dvornik.2017@gmail.com",
#     "is_staff": true,
#     "is_active": true,
#     "date_joined": "2021-05-20T15:33:55.838Z",
#     "groups": [],
#     "user_permissions": []
#   }


CATEGORY_CHOICES = (
    ('high_boots', 'Сапоги'),
    ('boots', 'Ботинки'),
    ('half_boots', 'П/ботинки'),
    ('shoes', 'Туфли'),
    ('summer_shoes', 'Туфли летние'),
    ('home_shoes', 'Домашняя обувь'),
    ('sport_shoes', 'Обувь для активного отдыха'),
)


OWNER_CHOICES = (
    ('M', 'Man'),
    ('W', 'Woman'),
    ('U', 'Unisex')
)


class SubImage(models.Model):
    title = models.CharField(max_length=100, default='Имя товара')
    image_1 = models.ImageField(null=True, blank=True)
    image_2 = models.ImageField(null=True, blank=True)
    image_3 = models.ImageField(null=True, blank=True)
    image_4 = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.title


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=26)
    owner = models.CharField(choices=OWNER_CHOICES, max_length=1, default='U')
    slug = models.SlugField(unique=True)
    description = models.TextField()
    image = models.ImageField()
    sub_images = models.OneToOneField(SubImage, blank=True, on_delete='SET_NULL', null=True, verbose_name='Дополнительные картинки')
    prioritize = models.IntegerField(blank=True, default=0)
    data_added = models.DateField(default=timezone.now, blank=True, null=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total


class ContactInfo(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.DO_NOTHING)
    letter = models.CharField(max_length=3000)
    destination_email = models.EmailField(max_length=100, default=settings.DEFAULT_CONTACT_EMAIL)

    def __str__(self):
        return f"This is a registered contact from user {self.user.username};\n" \
               f"Letter content: {self.letter};\n\n" \
               f"Dispatch address: {self.user.email};\n" \
               f"Destination address: {self.destination_email}."

django-ecommerce-master/core/forms.py
from django import forms


class Product(forms.Form):
    count = forms.IntegerField(label='Количество')


class Contact(forms.Form):
    letter = forms.CharField(label="Ваше сообщение", widget=forms.Textarea)
    destination_email = forms.EmailField(label="Ваша почта")


class AccountInfo(forms.Form):
    first_name = forms.CharField(label="Ваше имя", help_text="Введите имя",
                                 widget=forms.TextInput(attrs={'size': 35}))
    last_name = forms.CharField(label="Ваша фамилия", help_text="Введите фамилию",
                                widget=forms.TextInput(attrs={'size': 35}))
    user_email = forms.EmailField(label="Ваш E-mail", help_text="Введите E-mail",
                                  widget=forms.EmailInput(attrs={'size': 35}))

django-ecommerce-master/templates/account_info.html
{% extends "account/base.html" %}

{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Личный кабинет" %}{% endblock %}

{% block content %}
  <div class="account-page">

      <div class="container">

			<div class="row">

                <div class="account-side-small-img">

                    <img src="{% static 'img/images/women_shoes_account.png'%}" class="account-side-small-img">

                </div>

				<div class="col-2">

					<div class="form-container" id="account-info-form-container">

                        <div class="orange_rectangle" id="up-rect">
                          <img src="{% static 'img/images/registration_pic.png'%}" width="15%">
                        </div>

                        <div class="registration_content">

                              <form method="post" action="{% url 'core:account-info' %}">

                                  {% csrf_token %}

                                  <div id="div_id_first_name" class="form-group">

<!--                                    <label for="id_first_name" class="col-form-label  requiredField">Ваше имя</label>-->
                                      {{ form.first_name.label_tag }}
                                    <div class="">
<!--                                      <input type="text" name="first_name" placeholder="Введите имя" autofocus="autofocus" minlength="1" maxlength="150" class="textinput textInput form-control" required id="id_first_name">-->
                                      {{ form.first_name }}
                                    </div>
                                  </div>


                                  <div id="div_id_last_name" class="form-group">

<!--                                    <label for="id_last_name" class="col-form-label  requiredField">Ваша фамилия</label>-->
                                        {{ form.last_name.label_tag }}
                                    <div class="">
                                        {{ form.last_name }}
<!--                                      <input type="text" name="last_name" placeholder="Введите фамилию" class="textinput textInput form-control" required id="id_last_name">-->
                                    </div>

                                  </div>


                                  <div id="div_id_email" class="form-group">

<!--                                    <label for="id_email" class="col-form-label ">Ваш E-mail</label>-->
                                        {{ form.user_email.label_tag }}
                                    <div class="">
                                        {{ form.user_email }}
<!--                                      <input type="email" name="user_email" placeholder="Введите E-mail" class="textinput textInput form-control" id="id_email">-->
                                    </div>

                                  </div>

<!--                                  <div id="div_id_password2" class="form-group">-->

<!--                                    <label for="id_password2" class="col-form-label  requiredField">-->
<!--                                    Повторите пароль-->
<!--                                    </label>-->

<!--                                    <div class="">-->

<!--                                      <input type="password" name="password2" placeholder="Повторите пароль" class="textinput textInput form-control" required id="id_password2">-->

<!--                                    </div>-->

<!--                                  </div>-->

                                    <button class='btn btn-primary' type="submit">{% trans 'Сохранить' %} &raquo;</button>

                                  </form>

                        </div>

                        <div class="orange_rectangle" id="down-rect"></div>
                    </div>
				</div>

                <img src="{% static 'img/images/man_shoes_account.png'%}" class="account-side-small-img">

			</div>
		</div>


<div class="container" id="cart-container">
        <div class="table-responsive text-nowrap">
            <h2 id="main-title">Заказы в обработке</h2>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Информация о заказе</th>
                    <th scope="col">Стоимость заказа</th>
                </tr>
                </thead>
                <tbody>
                {% for order in orders %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>
                        {% for order_item in order.items.all %}

                        {{order_item.item.title}} в количестве {{order_item.quantity}}
                        <br>

                        {% endfor %}
                    </td>
                    <td>${{ order.get_total }}</td>

                </tr>
                {% empty %}
                <tr>
                    <td colspan='3'>Похоже вы еще ничего не заказали. Пожалуйста, выполните заказ для дальнейшей работы.</td>
                </tr>

                {% endfor %}

                </tbody>
            </table>

        </div>

    </div>
  </div>
{% endblock %}

django-ecommerce-master/templates/base.html
{% load static %}
{% load cart_template_tags %}

<!DOCTYPE html>

<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}{% endblock %}
    <link rel="shortcut icon" href="{% static 'img/images/favicon.png'%}" type="image/png">
	<link rel="stylesheet" href="{% static 'css/main_style.css' %}">
	<link rel="stylesheet" href="{% static 'font/font-awesome/css/font-awesome.min.css' %}">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap" rel="stylesheet">
</head>

<body>
	<div class="header">
		<div class="container">
				<div class="navbar">
					<div class="app-logo">
						<a href="{% url 'core:home' %}">
							<img src="{% static 'img/images/new_logo.png'%}">
						</a>
					</div>
					
					<nav>
						<ul id="MenuItems">
							<li><a href="{% url 'core:home' %}">Главная</a></li>
							<li><a href="{% url 'core:products' %}">Товары</a></li>
							<li><a href="{% url 'core:about' %}">О нас</a></li>
							<li><a href="{% url 'core:contact' %}">Связаться с нами</a></li>
							{% if request.user.is_authenticated %}
							<li><a href="{% url 'core:account-info' %}">{{ user.username }}</a></li>
							<li>
								<a href="{% url 'account_logout' %}">
								  <span> Выход </span>
								</a>
							</li>
							{% else %}
							<li>
								<a href="{% url 'account_login' %}">
									<span> Вход </span>
								</a>
							</li>
							<li>
								<a href="{% url 'account_signup' %}">
								  <span> Регестрация </span>
								</a>
							</li>
							{% endif %}
						</ul>
					</nav>

					<a href="{% url 'core:order-summary' %}">
					  <span> {{ request.user|cart_item_count }} </span>
					  <img src="{% static 'img/images/cart.png'%}" width="30px" height="30px">
					</a>

					<img src="{% static 'img/images/menu.png'%}" class="menu-icon" onclick="menutoggle()">
				</div>
			{% block intro_section %}{% endblock %}
		</div>
	</div>

<!--    <div class="messages-section">-->

<!--    	{% if messages %}-->

<!--		<ul class="messages">-->

<!--		    {% for message in messages %}-->

<!--		    	<li {% if message.tags %} class="{{ message.tags }}"-->
<!--				    {% endif %}>-->
<!--					{{ message }}-->
<!--				</li>-->

<!--		    {% endfor %}-->

<!--		</ul>-->

<!--		{% endif %}-->

<!--    </div>-->

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    <div class="footer">
		<div class="container">
			<div class="row">
				<div class="footer-col-1">
					<h3>Download Our App</h3>
					<p>Загрузите наше приложение на Android и Ios. </p>
					<div class="logo">
						<a href="https://play.google.com/store?hl=ru&gl=US">
							<img src="{% static 'img/images/play-store.png'%}">
						</a>
						<a href="https://apps.apple.com/ru/genre/ios/id36">
							<img src="{% static 'img/images/app-store.png'%}">
						</a>
					</div>
				</div>
				<div class="footer-col-2">
					<img src="{% static 'img/images/new_logo.png'%}">
					<p>Наша цель - ваше ежедневное удовольствие ! Сделаем все возможное, чтобы ваши ножки никогда не жаловались на жизнь.</p>
				</div>
				<div class="footer-col-3">
					<h3>Useful Links</h3>
					<ul>
						<a href="#">
							<li>Политика конфиденциальности</li>
						</a>
						<a href="#">
							<li>Политика Возврата</li>
						</a>
						<a href="#">
							<li>Купоны</li>
						</a>
						<a href="https://blog.poshmark.com/">
							<li>Наш Блог</li>
						</a>
					</ul>
				</div>
				<div class="footer-col-4">
					<h3>Follow us</h3>
					<ul>
						<a href="https://vk.com/tvoi_dvorik">
							<li>VK</li>
						</a>
						<a href="#">
							<li>Facebook</li>
						</a>
						<a href="#">
							<li>Twitter</li>
						</a>
						<a href="https://www.instagram.com/dv_maks0_0/">
							<li>Instagram</li>
						</a>
						<a href="#">
							<li>YouTube</li>
						</a>
					</ul>
				</div>
			</div>
			<hr>
			<p class="copyright">Copyright 2022 - M/W Shoes</p>
		</div>
	</div>

    <script>
		var MenuItems = document.getElementById("MenuItems");
		MenuItems.style.maxHeight = "0px";
		function menutoggle(){
			if (MenuItems.style.maxHeight == "0px")
			{
				{% if not request.user.is_authenticated %}

				MenuItems.style.maxHeight = "250px";

				{% else %}
				MenuItems.style.maxHeight = "220px";
				{% endif %}
			}

			else
			{
				MenuItems.style.maxHeight = "0px";
			}
		}
	</script>

    {% block extra_scripts %}{% endblock extra_scripts %}

</body>
</html>

django-ecommerce-master/templates/home.html
{% extends "base.html" %}

{% load static %}

{% block head_title %}
M/W shoes - Главная
{% endblock %}

<!--intro section -->
{% block intro_section %}

	<div class="row">
		<div class="col-2">
			<h1>Наполните свою жизнь счастьем вместе с нами !</h1>
			<p>“Дорога к успеху – это всегда дорога в гору, и чтобы подняться в нее, всего-то нужно иметь пару новенькой обуви от M/W Shoes.”
			</p>
			<a href="{% url 'core:products' %}" class="btn">Начни сейчас &#x261B;</a>
		</div>

		<div class="col-2">
			<img src="{% static 'img/images/intro-buying.png'%}">
		</div>
	</div>

{% endblock %}

{% block content %}

<!--featured categories -->
<div class="categories">
	<div class="small-container">
		<h2 class="title">Категории</h2>
		<div class="row">

			<div class="col-3"> 
				<a href="{% url 'core:show-main-category' 'M'%}">
					<img src="{% static 'img/images/category-m.jpg'%}" class="category-img">
				</a>
			</div>

			<div class="col-3">
				<a href="{% url 'core:show-main-category' 'W'%}">
					<img src="{% static 'img/images/category-w.jpg'%}" class="category-img">
				</a>
			</div>

			<div class="col-3">
				<a href="{% url 'core:show-main-category' 'U'%}">
					<img src="{% static 'img/images/category-unisex.jpg'%}" class="category-img">
				</a>
			</div>

		</div>
	</div>
</div>


		<h2 class="title">Новинки</h2>

		<div class="row">
			{% for item in sorted_items %}

				<div class="col-4">

					<a href="{{ item.get_absolute_url }}"><img src="{{ item.image.url }}">
					</a>

					<h5>{{ item.get_category_display }}</h5>

					<a href="{{ item.get_absolute_url }}">
						{{ item.title }}
	                </a>

					<p>
						  {% if item.discount_price %}

		                  {{ item.discount_price }}

		                  {% else %}

		                  {{ item.price }}

		                  {% endif %}
		                  BYN
	                </p>

				</div>

				{% endfor %}

		</div>


<!-- offer -->
	<div class="offer">
		<div class="small-container">
			<div class="row">

<!--				<div class="col-2">-->
<!--					<img src="{{most_popular_item.image.url}}" class="offer-img">-->
<!--				</div>-->
				<div class="col-2">
					<h1>Самый популярный товар на сайте</h1>
					<img src="{{ most_popular_item.image.url }}" id="popular_item_img">

					<h2>{{most_popular_item.title}}</h2>
					<br>
					<h3>{{ most_popular_item.get_category_display }}</h3>
					<br>
					<small>{{most_popular_item.description}}</small>
					<br>
					<a href="{% url 'core:product' most_popular_item.slug %}" class="btn">Купить сейчас &#x261B;</a>
				</div>

			</div>
		</div>
	</div>

<!-- testimonial -->
	
	<h2 class="title" id="response-label">Отзывы</h2>

	<div class="testimonial">
		<div class="small-container">
			<div class="row">
				<div class="col-3">
					<i class="fa fa-quote-left"></i>
					<p>Большой выбор, приятные цены. Очень доброжелательный персонал! Спасибо.</p>
					<div class="rating">
						<i class="fa fa-star"></i>
						<i class="fa fa-star"></i>
						<i class="fa fa-star"></i>
						<i class="fa fa-star"></i>
						<i class="fa fa-star-o"></i>
					</div>
					<img src="{% static 'img/images/user-1.png'%}">
					<h3>Иванова Вероника</h3>
				</div>
				<div class="col-3">
					<i class="fa fa-quote-left"></i>
					<p>Магазин с огромным ассортиментом. Прекрасно и логично размещено. Очень чисто.
					Радует магазин и приятными ценами. Здесь всегда есть скидки и сложно уйти без покупки. Каждый найдет себе пару на любую ногу.
					Обслуживание на высшем уровне: вежливое, внимательное, предупредительное.
					Рекомендую зайти и убедиться самим.
					</p>
					<div class="rating">
						<i class="fa fa-star"></i>
						<i class="fa fa-star"></i>
						<i class="fa fa-star"></i>
						<i class="fa fa-star"></i>
						<i class="fa fa-star"></i>
					</div>
					<img src="{% static 'img/images/user-2.png'%}">
					<h3>Mike Pirce</h3>
				</div>
				<div class="col-3">
					<i class="fa fa-quote-left"></i>
					<p>I’ve tested several shoes from Adidas, but this is my first time buying such a good thing for a good price. Thank you, M/W Shoes.</p>
					<div class="rating">
						<i class="fa fa-star"></i>
						<i class="fa fa-star"></i>
						<i class="fa fa-star"></i>
						<i class="fa fa-star"></i>
						<i class="fa fa-star-o"></i>
					</div>
					<img src="{% static 'img/images/user-3.png'%}">
					<h3>Mabel Joe</h3>
				</div>
			</div>
		</div>
	</div>

	<!-- brands -->
	<div class="brands">
		<div class="small-container">
			<h2 class="title">Наши партнеры</h2>
			<div class="row">
				<div class="col-5">
					<a href="https://www.nike.com/">
						<img src="{% static 'img/images/logo-nike.png'%}">
					</a>
				</div>
				<div class="col-5">
					<a href="https://by.wildberries.ru/">
						<img src="{% static 'img/images/logo-wildberries.png'%}">
					</a>
				</div>
				<div class="col-5">
					<a href="https://www.nike.com/ru/jordan">
						<img src="{% static 'img/images/logo-jordan.png'%}">
					</a>
					
				</div>
				<div class="col-5">
					<a href="https://megatop.by/">
						<img src="{% static 'img/images/logo-megatop.png'%}">
					</a>
				</div>
				<div class="col-5">
					<a href="http://www.marko.by/">
						<img src="{% static 'img/images/marko-logo.png'%}">
					</a>
				</div>
			</div>
		</div>
	</div>

{% endblock content %}

django-ecommerce-master/templates/order_summary.html
{% extends "base.html" %}

{% load static %}

{% block head_title %}
M/W shoes - Cart
{% endblock %}


{% block content %}


    <div class="container" id="cart-container">
        <div class="table-responsive text-nowrap">
            <h2 id="main-title">Корзина</h2>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Название</th>
                    <th scope="col">Цена</th>
                    <th scope="col">Количество</th>
                    <th scope="col">Денег сэкономлено</th>
                    <th scope="col">Общая цена</th>
                </tr>
                </thead>
                <tbody>
                {% for order_item in object.items.all %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ order_item.item.title }}</td>
                    <td>{{ order_item.item.price }}</td>
                    <td>
                        <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fa fa-minus" aria-hidden="true"></i></a>
                        {{ order_item.quantity }}
                        <a href="{% url 'core:add-single-item-to-cart' order_item.item.slug %}"><i class="fa fa-plus" aria-hidden="true"></i></a>
                    </td>
                    <td>
                        {% if order_item.item.discount_price %}
                            <span>${{ order_item.get_amount_saved }}</span>
                        {% else %}
                            <span>Скидка отсутствует</span>
                        {% endif %}
                    </td>
                    <td>
                        {% if order_item.item.discount_price %}
                            ${{ order_item.get_total_discount_item_price }}
                        {% else %}
                            ${{ order_item.get_total_item_price }}
                        {% endif %}
                        <a style='color: red;' href="{% url 'core:remove-all-items-from-cart' order_item.item.slug %}">
                            <i class="fa fa-trash" aria-hidden="true"></i>
                        </a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan='6'>Ваша корзина пуста. Для работы с ней, пожалуйста, добавьте желаемые товары.</td>
                </tr>

                {% endfor %}

                {% if object.get_total %}

                <tr>
                    <td colspan="5"><b>Сумма заказа</b></td>
                    <td><b>${{ object.get_total }}</b></td>
                </tr>

                {% endif %}
                </tbody>
            </table>
            <br>
            <br>
            <a class='btn btn-primary float-right' href="{% url 'core:products' %}">Продолжить покупки</a>

            {% if object.get_total %}
            <a class='btn btn-primary float-right' href="{% url 'core:confirm-offer' %}">Подтвердить заказ</a>
            {% endif %}
        </div>

    </div>
  


{% endblock content %}

django-ecommerce-master/templates/product.html
{% extends "base.html" %}

{% load static %}

{% block head_title %}
M/W shoes - {{ item.title }}
{% endblock %}


{% block content %}

	<!-- single product details -->
	<!-- single-product -->

<div class="small-container single-product">

	<div class="row" id="images-row">
		
		<div class="col-2" id="product-images">
			<img src="{{ item.image.url }}" width="100%" id="ProductImg">

			<div class="small-img-row">

				{% if sub_images.image_1 %}

				<div class="small-img-col">
					<img src="{{ sub_images.image_1.url }}" width="100%" class="small-img">
				</div>

				{% endif %}

				{% if sub_images.image_2 %}

				<div class="small-img-col">
					<img src="{{ sub_images.image_2.url }}" width="100%" class="small-img">
				</div>

				{% endif %}

				{% if sub_images.image_3 %}

				<div class="small-img-col">
					<img src="{{ sub_images.image_3.url }}" width="100%" class="small-img">
				</div>

				{% endif %}

				{% if sub_images.image_4 %}

				<div class="small-img-col">
					<img src="{{ sub_images.image_4.url }}" width="100%" class="small-img">
				</div>

				{% endif %}


			</div>
		</div>

		<div class="col-2" id="item-details">
			<p>{{item.get_category_display}} / {{ item.title }}</p>
			<h1>{{ item.title }}</h1>
			<h4>
				  {% if item.discount_price %}

                  {{ item.discount_price }}

                  {% else %}

                  {{ item.price }}

                  {% endif %}
                  BYN
	        </h4>

			<form action="{% url 'core:product' item.slug %}" method="post" class="product-main-form">
				
				{% csrf_token %}
				
				<div class="form-group">

				{% for field in form %}					    
				    
				    <div class="row-form">
			            {{field.label_tag}}
			            <div class="field">
							<input type="number" name="count" required="" id="id_count" min="0">
			        	</div>
			            {% if field.errors%}
			            <div class="form-error">
			            	{{field.errors}}
			        	</div>
			            {% endif %}
			        </div>

				{% endfor %} 
			    
				</div>

				<input id="form-btn" class="btn" type="submit" value="В корзину" name="add_cart">
				<input id="form-btn" class="btn" type="submit" value="Удалить" name="delete_cart">

		    </form>

			<h3>Product Details <i class="fa fa-indent"></i></h3>
			<br>
			<p>{{item.description}}</p>
		</div>
		
	</div>
</div>
	<!-- title -->

	<div class="small-container">
		<div class="row row-2">
			<h2>Related Products</h2>
			<a href="{% url 'core:show-main-category' item.owner %}">View more</a>
		</div>
	</div>

	<!-- products -->

	<div class="small-container">
		
		<div class="row">


		{% for rel_item in object_list %}

			{% if rel_item.owner == item.owner %}

				<div class="col-4">
					
					<img src="{{ rel_item.image.url }}">
					
					<h5>{{ rel_item.get_category_display }}</h5>

					<a href="{{ rel_item.get_absolute_url }}">
						{{ rel_item.title }}
	                </a>

					<p>	
						  {% if rel_item.discount_price %}

		                  {{ rel_item.discount_price }}

		                  {% else %}

		                  {{ rel_item.price }}

		                  {% endif %}
		                  BYN
	                </p>

				</div>

			{% endif %}

		{% endfor %}

			
		</div>
	</div>

{% endblock content %}

 {% block extra_scripts %}

 <!-- js for product gallery -->

	<script>
		var ProductImg = document.getElementById("ProductImg");
		var SmallImg = document.getElementsByClassName("small-img");
			
			SmallImg[0].onclick = function()
			{
				ProductImg.src = SmallImg[0].src;
			}
			SmallImg[1].onclick = function()
			{
				ProductImg.src = SmallImg[1].src;
			}
			SmallImg[2].onclick = function()
			{
				ProductImg.src = SmallImg[2].src;
			}
			SmallImg[3].onclick = function()
			{
				ProductImg.src = SmallImg[3].src;
			}
	</script>

 {% endblock extra_scripts %}